apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-pv-jegan # Replace 'jegan' with your name
  labels:
    name: jegan # Replace 'jegan' with your name
spec:
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  peristentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.1.108 #Replace this IP with your RDP Linu Server IP
    path: /var/nfs/jegan/wordpress # Replace this path with your path /var/nfs/user[xy]/wordpress
