apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mongodb
  name: mongodb
spec:
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      volumes:
      - name: mongodb-storage
        persistentVolumeClaim:
          claimName: mongodb-pvc-jegan # Replace 'jegan' with your name
      containers:
      - image: bitnami/mongodb:latest
        name: mongodb
        imagePullPolicy: IfNotPresent
        env:
        - name: MONGODB_PASSWORD 
          value: root@123

        volumeMounts:
        - name: mongodb-storage
          mountPath: /bitnami/mongodb/data
