apiVersion: batch/v1
kind: Job
metadata:
  name: hello-job
spec:
  template:
    spec:
      containers:
      - name: job-container
        image: busybox
        command: ["sh", "-c", "echo 'Hello Job Started' && sleep 20 && exit 0"]
      restartPolicy: Never
