apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-pv-{{.Values.pv.label}}
  labels:
    name: {{.Values.pv.label}}
spec:
  capacity:
    storage: {{.Values.pv.wordpress_disk_size}} 
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  peristentVolumeReclaimPolicy: Retain
  nfs:
    server: {{.Values.nfs.server_ip}} 
    path: {{.Values.nfs.wordpress_path}} 
