apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-pvc-{{.Values.pv.label}}
spec:
  selector:
    matchLabels:
      name: {{.Values.pv.label}}
  accessModes:
  - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{.Values.pv.wordpress_disk_size}} 
