apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: wordpress
  name: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      volumes:
      - name: wordpress-storage
        persistentVolumeClaim:
          claimName: wordpress-pvc-{{.Values.pv.label}}
      containers:
      - image: bitnami/wordpress:latest
        name: wordpress
        imagePullPolicy: IfNotPresent

        volumeMounts:
        - name: wordpress-storage
          mountPath: /bitnami/wordpress
        env:
        - name: WORDPRESS_DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: wordpress-secret
              key: username 

        - name: WORDPRESS_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wordpress-secret
              key: password 

        - name: WORDPRESS_DATABASE_NAME
          valueFrom:
            configMapKeyRef:
              name: wordpress-cm
              key: db_name

        - name: WORDPRESS_DATABASE_HOST
          valueFrom:
            configMapKeyRef:
              name: wordpress-cm
              key: db_host

        - name: WORDPRESS_DATABASE_PORT_NUMBER
          valueFrom:
            configMapKeyRef:
              name: wordpress-cm
              key: db_port
