apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mysql
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  strategy: {}
  template:
    metadata:
      labels:
        app: mysql
    spec:
      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: mysql-pvc-jegan # Replace 'jegan' with your name
      containers:
      - image: bitnami/mysql:latest
        name: mysql
        imagePullPolicy: IfNotPresent

        volumeMounts:
        - name: mysql-storage
          mountPath: /bitnami/mysql/data
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: root@123
